### ISSUE TITLE
OS Provisioning

### ISSUE THREAD

**Issue by benjamin-s-hobbs** [GSD-Solutions-Group/Project#10]
Skip processes that take a long time to complete. Remember, your demo time is limited.

**Comment by nsiramarco** [comment]
Presentation- Demonstrate customization and provisioning of the required OS.
User provisioning:
Setup a single endpoint as you would for a new user:
This should include connecting the new user to whatever network or cloud resources they will use (shared folders, backup systems, email address connected to email client, etc.).
Use any available tooling to minimize MSP labor in this process.
Stretch Goal: partially or fully automate this process (imagine entering only the new user’s name and email into a script and then letting the setup take care of itself).
