### ISSUE TITLE
Presentation-Backup Solution- Bacula

### ISSUE THREAD

**Issue by benjamin-s-hobbs** [GSD-Solutions-Group/Project#15]
How will your MSP mitigate the risk of data loss on this new computer system? Your presentation should mention as well how you would perform a baremetal restoration if the OS were to be rendered inoperable.

**Comment by nsiramarco** [comment]
GUIDLINE REQUIREMENT:
Backup Solution:
User endpoints will need a backup solution.
Backups should:
Preserve user data.
Minimize user downtime in the event of system failure.

PRESENTATION:
Demonstrate a single file or folder data backup and restoration procedure.
How will your MSP mitigate the risk of data loss on this new computer system? Your presentation should mention as well how you would perform a baremetal restoration if the OS were to be rendered inoperable.
